spring:
  profiles:
    active: dev


---

server:
  port: 7001

#spring配置
spring:
  profiles: dev
  application:
    name: springcloud-config-eureka

#配置Eureka注册中心
eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示向Euraka注册中心注册自己
    fetch-registry: false #fetch-registry如果为false，则表示自己为注册中心
    service-url: #监控页面
      #单机：http://${eureka.instance.hostname}:${server.port}
      #集群(关联）:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---
server:
  port: 7001

#spring配置
spring:
  profiles: test
  application:
    name: springcloud-config-eureka

#配置Eureka注册中心
eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示向Euraka注册中心注册自己
    fetch-registry: false #fetch-registry如果为false，则表示自己为注册中心
    service-url: #监控页面
      #单机：http://${eureka.instance.hostname}:${server.port}
      #集群(关联）:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/